// Auto-generated by SSBD Admin — do not edit manually
const translations = {
  "en": {
    "cta_btn": "Let's Talk →",
    "cta_subtitle": "Tell us about your event and we'll get back to you within 24 hours.",
    "cta_title": "Ready to make your event unforgettable?",
    "footer_company": "Company",
    "footer_contact": "Contact",
    "footer_desc": "Boutique sound & lighting rental for events in Dubai and across the UAE.",
    "footer_services": "Services",
    "hero_cta_primary": "Tell Us About Your Event →",
    "hero_cta_secondary": "See Our Work",
    "hero_subtitle": "Boutique audio & lighting specialists in Dubai — weddings, corporate events & private parties across the UAE",
    "hero_title": "Sound & Light That Transforms Events",
    "nav_about": "About",
    "nav_blog": "Blog",
    "nav_contact": "Let's Talk",
    "nav_lighting": "Lighting Rental",
    "nav_portfolio": "Portfolio",
    "nav_services": "Services",
    "nav_sound": "Sound Rental",
    "portfolio_btn": "View All Projects →",
    "portfolio_label": "Portfolio",
    "portfolio_title": "Recent Work",
    "services_label": "Our Expertise",
    "services_lighting_link": "Explore Lighting Services →",
    "services_lighting_text": "The right light changes everything. Moving heads, wash lights, uplighting, and atmospheric effects — designed to set the exact mood your event deserves.",
    "services_lighting_title": "Event Lighting",
    "services_sound_link": "Explore Sound Services →",
    "services_sound_text": "From intimate private parties to large corporate conferences — crystal-clear audio tailored to your venue and audience. We bring top-tier PA systems, mixing consoles, and our expertise to every event.",
    "services_sound_title": "Professional Sound",
    "services_title": "What We Do",
    "testimonial_author": "— Event Manager, Dubai",
    "testimonial_quote": "The sound at our product launch was flawless. The team understood exactly what we needed and delivered without any stress on our end.",
    "trust_label": "Equipment we trust",
    "why_1_text": "We're a small team of three. That means you deal directly with the people doing the work — no account managers, no miscommunication.",
    "why_1_title": "Boutique, Not Corporate",
    "why_2_text": "We don't do everything. We do two things exceptionally well. No LED screens, no staging, no SFX packages — just perfect sound and precise lighting.",
    "why_2_title": "Sound & Light Only",
    "why_3_text": "We listen first. Each setup is tailored to your venue, your crowd, and your vision. Cookie-cutter solutions are not our style.",
    "why_3_title": "Every Event Is Different",
    "why_label": "The Difference",
    "why_title": "Why Same Same But Different?"
  },
  "ru": {
    "cta_btn": "Получить бесплатную квоту →",
    "cta_subtitle": "Расскажите нам о вашем мероприятии, и мы ответим в течение 24 часов.",
    "cta_title": "Готовы сделать ваше мероприятие незабываемым?",
    "footer_company": "Компания",
    "footer_contact": "Контакты",
    "footer_desc": "Бутик-аренда звука и света для мероприятий в Дубае и по всем ОАЭ.",
    "footer_services": "Услуги",
    "hero_cta_primary": "Расскажите нам о вашем мероприятии →",
    "hero_cta_secondary": "Наши работы",
    "hero_subtitle": "Boutique-специалисты по аудио и свету в Дубае — свадьбы, корпоративные мероприятия и частные вечеринки по всем ОАЭ",
    "hero_title": "Звук и Свет, Которые Преображают Мероприятия",
    "nav_about": "О нас",
    "nav_blog": "Блог",
    "nav_contact": "Написать нам",
    "nav_lighting": "Аренда света",
    "nav_portfolio": "Портфолио",
    "nav_services": "Услуги",
    "nav_sound": "Аренда звука",
    "portfolio_btn": "Смотреть все проекты →",
    "portfolio_label": "Портфолио",
    "portfolio_title": "Последние работы",
    "services_label": "Наша экспертиза",
    "services_lighting_link": "Узнать больше о свете →",
    "services_lighting_text": "Правильный свет меняет всё. Поворотные головы, заливающий свет, подсветка и атмосферные эффекты — спроектированные для создания именно того настроения, которое заслуживает ваше мероприятие.",
    "services_lighting_title": "Световое оформление",
    "services_sound_link": "Узнать больше о звуке →",
    "services_sound_text": "От камерных частных вечеринок до крупных корпоративных конференций — кристально чистый звук, адаптированный под ваше пространство и аудиторию. Мы привозим первоклассные PA-системы, микшерные пульты и наш опыт на каждое мероприятие.",
    "services_sound_title": "Профессиональный звук",
    "services_title": "Что мы делаем",
    "testimonial_author": "— Менеджер мероприятий, Дубай",
    "testimonial_quote": "Звук на нашем запуске продукта был безупречным. Команда точно поняла, что нам нужно, и всё сделала без стресса с нашей стороны.",
    "trust_label": "Оборудование, которому мы доверяем",
    "why_1_text": "Мы — маленькая команда из трёх человек. Это значит, что вы общаетесь напрямую с теми, кто выполняет работу — без менеджеров по продажам, без потери информации.",
    "why_1_title": "Бутик, а не корпорация",
    "why_2_text": "Мы не делаем всё подряд. Мы делаем две вещи исключительно хорошо. Никаких LED-экранов, сцен, SFX-пакетов — только идеальный звук и точный свет.",
    "why_2_title": "Только звук и свет",
    "why_3_text": "Мы сначала слушаем. Каждая инсталляция адаптирована под ваше пространство, вашу аудиторию и ваше видение. Шаблонные решения — не наш стиль.",
    "why_3_title": "Каждое мероприятие уникально",
    "why_label": "Наше отличие",
    "why_title": "Почему Same Same But Different?"
  }
};

// --- i18n Engine ---
function getCurrentLang() {
  return localStorage.getItem('ssbd_lang') || 'en';
}

function setLanguage(lang) {
  localStorage.setItem('ssbd_lang', lang);
  applyLanguage(lang);
  updateLangSwitcher(lang);
  // RTL support for future Arabic
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
}

function applyLanguage(lang) {
  const t = translations[lang] || translations.en;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });
}

function updateLangSwitcher(lang) {
  document.querySelectorAll('.lang-switch__btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

// Init on DOMContentLoaded
document.addEventListener('DOMContentLoaded', () => {
  const lang = getCurrentLang();
  applyLanguage(lang);
  updateLangSwitcher(lang);

  // Bind switcher buttons
  document.querySelectorAll('.lang-switch__btn').forEach(btn => {
    btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
  });
});
