const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

const ROOT = path.join(__dirname, '..', '..');
const TRANSLATIONS_JSON = path.join(ROOT, 'data', 'translations.json');
const TRANSLATIONS_JS = path.join(ROOT, 'js', 'translations.js');

const I18N_ENGINE = `
// --- i18n Engine ---
function getCurrentLang() {
  return localStorage.getItem('ssbd_lang') || 'en';
}

function setLanguage(lang) {
  localStorage.setItem('ssbd_lang', lang);
  applyLanguage(lang);
  updateLangSwitcher(lang);
  // RTL support for future Arabic
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
}

function applyLanguage(lang) {
  const t = translations[lang] || translations.en;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });
}

function updateLangSwitcher(lang) {
  document.querySelectorAll('.lang-switch__btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

// Init on DOMContentLoaded
document.addEventListener('DOMContentLoaded', () => {
  const lang = getCurrentLang();
  applyLanguage(lang);
  updateLangSwitcher(lang);

  // Bind switcher buttons
  document.querySelectorAll('.lang-switch__btn').forEach(btn => {
    btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
  });
});
`;

function getGitHubToken() {
  try {
    const envPath = path.join(ROOT, '.env');
    const env = fs.readFileSync(envPath, 'utf8');
    const match = env.match(/^GITHUB_TOKEN=(.+)$/m);
    return match ? match[1].trim() : null;
  } catch {
    return null;
  }
}

function regenerateTranslationsJS() {
  const data = JSON.parse(fs.readFileSync(TRANSLATIONS_JSON, 'utf8'));
  const content = `// Auto-generated by SSBD Admin — do not edit manually\nconst translations = ${JSON.stringify(data, null, 2)};\n${I18N_ENGINE}`;
  fs.writeFileSync(TRANSLATIONS_JS, content);
}

function deployToGitHub() {
  // Always regenerate translations.js from the current translations.json
  regenerateTranslationsJS();

  const token = getGitHubToken();
  const pushUrl = token
    ? `https://${token}@github.com/AdriDubai/ssbd-website.git`
    : 'origin';

  const cmd = `cd ${ROOT} && git add -A && git commit -m "Admin update $(date '+%Y-%m-%d %H:%M:%S')" && git push ${pushUrl} main`;

  exec(cmd, (err, stdout, stderr) => {
    if (err) console.error('Deploy error:', err.message);
    else console.log('Deployed:', stdout || 'OK');
  });
}

module.exports = { deployToGitHub };
