const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const ROOT = path.join(__dirname, '..', '..');
const TRANSLATIONS_JSON = path.join(ROOT, 'data', 'translations.json');
const TRANSLATIONS_JS = path.join(ROOT, 'js', 'translations.js');

const I18N_ENGINE = `
// --- i18n Engine ---
function getCurrentLang() {
  return localStorage.getItem('ssbd_lang') || 'en';
}

function setLanguage(lang) {
  localStorage.setItem('ssbd_lang', lang);
  applyLanguage(lang);
  updateLangSwitcher(lang);
  // RTL support for future Arabic
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
}

function applyLanguage(lang) {
  const t = translations[lang] || translations.en;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });
}

function updateLangSwitcher(lang) {
  document.querySelectorAll('.lang-switch__btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

// Init on DOMContentLoaded
document.addEventListener('DOMContentLoaded', () => {
  const lang = getCurrentLang();
  applyLanguage(lang);
  updateLangSwitcher(lang);

  // Bind switcher buttons
  document.querySelectorAll('.lang-switch__btn').forEach(btn => {
    btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
  });
});
`;

function regenerateTranslationsJS(data) {
  const content = `// Auto-generated by SSBD Admin — do not edit manually\nconst translations = ${JSON.stringify(data, null, 2)};\n${I18N_ENGINE}`;
  fs.writeFileSync(TRANSLATIONS_JS, content);
}

function autoCommitAndPush(message) {
  const git = (args) =>
    new Promise((resolve) => {
      execFile('git', args, { cwd: ROOT }, (err, stdout, stderr) => {
        resolve({ err, stdout: stdout?.trim(), stderr: stderr?.trim() });
      });
    });

  // Run in background — don't block the HTTP response
  (async () => {
    try {
      await git(['add', '-A']);
      const { err } = await git(['commit', '-m', message || 'Admin: content update']);
      if (err) return; // nothing to commit
      await git(['push']);
    } catch (e) {
      console.error('Auto-publish failed:', e.message);
    }
  })();
}

function publishAfterTranslationsSave(data) {
  regenerateTranslationsJS(data);
  autoCommitAndPush('Admin: translations update');
}

function publishAfterContentSave(label) {
  autoCommitAndPush(`Admin: ${label} update`);
}

module.exports = {
  regenerateTranslationsJS,
  autoCommitAndPush,
  publishAfterTranslationsSave,
  publishAfterContentSave,
};
